apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-app
  template:
    metadata:
      labels:
        app: ml-app
    spec:
      containers:
      - name: ml-app-container
        image: gcr.io/anime-recommender-mlops/ml-project:latest
        ports:
        - containerPort: 5000  # Replace with the port your app listens on
        env:
        - name: COMET_API_KEY
          value: "${COMET_API_KEY}"
        - name: COMET_PROJECT_NAME
          value: "${COMET_PROJECT_NAME}"
        - name: COMET_WORKSPACE
          value: "${COMET_WORKSPACE}"
---
apiVersion: v1
kind: Service
metadata:
  name: ml-app-service
spec:
  type: LoadBalancer
  selector:
    app: ml-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000